language: ruby

sudo: true

rvm:
  - 2.1.2

before_install:
  - sudo apt-get update

before_script:
  - sudo apt-get install hunspell -y
  - find . -iname *.md -type f -exec hunspell -l {} \;

notifications:
  slack: djg:N3jInrNM7K6PfRz2EglMUmeF
# script: