## GitPages + Jekyll setup
name: Dorel.io
title: Service Design Guide
description: Service Design Guide information
theme: minima # github pages only supports minima theme

## Gitpages
baseurl: /

## Jekyll setup
markdown:    kramdown

## directories
assets_dir: /assets
bower_dir: /assets/bower_components

style_cdn: https://cdn.dorel.io/
style_cdn_brands_dir: https://cdn.dorel.io/includes/brands/