## GitPages + Jekyll setup
name: Dorel.io
title: Service Design Guide
description: Service Design Guide information
theme: minima # github pages only supports minima theme

## Gitpages
baseurl: /

## Jekyll setup
markdown:    kramdown

## directories
assets_dir: /assets
bower_dir: /assets/bower_components
custom_component_dir: /assets/custom_components

## style
cdn_style: https://dev.cdn.dorel.io