## GitPages + Jekyll setup
name: Dorel.io
title: Service Design Guide
description: Service Design Guide information
theme: minima # github pages only supports minima theme

## Jekyll setup
source:       ./source/site
# destination:  ./_site
# plugins_dir:  _plugins
# layouts_dir:  _layouts
# data_dir:     _data
# includes_dir: _includes
collections:
  service-manual:
    output: true
  technology:
    output: true
    permalink: /service-manual/:collection/:path/
  agile:
    output: true
    permalink: /service-manual/:collection/:path/
  helping-people-to-use-your-service:
    output: true
    permalink: /service-manual/:collection/:path/
  making-software:
    output: true
    permalink: /service-manual/:collection/:path/
  measurement:
    output: true
    permalink: /service-manual/:collection/:path/
  user-centred-design:
    output: true
    permalink: /service-manual/:collection/:path/

# # Handling Reading
# safe:         false
# include:      [".htaccess"]
# exclude:      []
# keep_files:   [".git", ".svn"]
# encoding:     "utf-8"
# markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# # Filtering Content
# show_drafts: null
# limit_posts: 0
# future:      false
# unpublished: false

# # Plugins
# whitelist: []
# gems:      []

# # Conversion
# markdown:    kramdown
# highlighter: rouge
# lsi:         false
# excerpt_separator: "\n\n"
# incremental: false

# # Serving
# detach:  false
# port:    4000
# host:    127.0.0.1
# baseurl: "" # does not include hostname
# show_dir_listing: false

# # Outputting
# permalink:     none
# paginate_path: /page:num
# timezone:      null

# quiet:    false
