## GitPages + Jekyll setup
name: Dorel.io
description: Service design guide
theme: minima # github pages only supports minima theme

## Jekyll setup
source:       ./source/site
# destination:  ./_site
# plugins_dir:  _plugins
# layouts_dir:  _layouts
# data_dir:     _data
# includes_dir: _includes
collections:
  # posts:
  #   output: true
  service-manual:
    output: true
    # permalink: "/service-manual/:path/"
  service-manual/agile:
    output: true
  service-manual/helping-people-to-use-your-service:
    output: true
  srevice-manual/making-software:
    output: true
  srevice-manual/measurement:
    output: true
  service-manual/technology:
    output: true
  service-manual/user-centred-design:
    output: true

# # Handling Reading
# safe:         false
# include:      [".htaccess"]
# exclude:      []
# keep_files:   [".git", ".svn"]
# encoding:     "utf-8"
# markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# # Filtering Content
# show_drafts: null
# limit_posts: 0
# future:      false
# unpublished: false

# # Plugins
# whitelist: []
# gems:      []

# # Conversion
# markdown:    kramdown
# highlighter: rouge
# lsi:         false
# excerpt_separator: "\n\n"
# incremental: false

# # Serving
# detach:  false
# port:    4000
# host:    127.0.0.1
# baseurl: "" # does not include hostname
# show_dir_listing: false

# # Outputting
# permalink:     date
# paginate_path: /page:num
# timezone:      null

# quiet:    false
